services:
  accommodation:
    container_name: accommodation
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: unless-stopped
    volumes:
      - ../../ELK-stack/secrets/certs:/app/certs
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres
  
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: accommodation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  default:
    name: bukiteasy
    external: true